spring:
  application:
    name: filmmanagement-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moviesactorsdb?useSSL=false&serverTimezone=Europe/Madrid&allowPublicKeyRetrieval=true
    username: root
    password:
  jpa:
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}

